// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iihglshgcfbtbocdjdqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpaGdsc2hnY2ZidGJvY2RqZHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjgwNzcsImV4cCI6MjA2Mzk0NDA3N30.Nb2zYMnk60ntR5xhVi7sgWGq9-EwwJWdMDuErJhXYJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);